version: '3.4'

services:
  app:
    image: node:alpine
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - mysql
    volumes:
      - ./../../:/app
    working_dir: /app
  mysql:
    container_name: mysql_db
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=smialowski
      - MYSQL_USER=lukasz
      - MYSQL_PASSWORD=smialowski
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - "./../../data/mysql:/var/lib/mysql"
